name: Setup apps-rendering
runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-    
    - name: install
      run: npm ci
