/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IContentAtomElementFieldsArgs {
    atomId: string;
    atomType: string;
}
export class ContentAtomElementFields {
    public atomId: string;
    public atomType: string;
    constructor(args: IContentAtomElementFieldsArgs) {
        if (args != null && args.atomId != null) {
            this.atomId = args.atomId;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[atomId] is unset!");
        }
        if (args != null && args.atomType != null) {
            this.atomType = args.atomType;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[atomType] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ContentAtomElementFields");
        if (this.atomId != null) {
            output.writeFieldBegin("atomId", thrift.TType.STRING, 1);
            output.writeString(this.atomId);
            output.writeFieldEnd();
        }
        if (this.atomType != null) {
            output.writeFieldBegin("atomType", thrift.TType.STRING, 2);
            output.writeString(this.atomType);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ContentAtomElementFields {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldType;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.atomId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.atomType = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.atomId !== undefined && _args.atomType !== undefined) {
            return new ContentAtomElementFields(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read ContentAtomElementFields from input");
        }
    }
}
