/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ICrosswordDimensionsArgs {
    cols: number;
    rows: number;
}
export class CrosswordDimensions {
    public cols: number;
    public rows: number;
    constructor(args: ICrosswordDimensionsArgs) {
        if (args != null && args.cols != null) {
            this.cols = args.cols;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[cols] is unset!");
        }
        if (args != null && args.rows != null) {
            this.rows = args.rows;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[rows] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CrosswordDimensions");
        if (this.cols != null) {
            output.writeFieldBegin("cols", thrift.TType.I32, 1);
            output.writeI32(this.cols);
            output.writeFieldEnd();
        }
        if (this.rows != null) {
            output.writeFieldBegin("rows", thrift.TType.I32, 2);
            output.writeI32(this.rows);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CrosswordDimensions {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.cols = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: number = input.readI32();
                        _args.rows = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.cols !== undefined && _args.rows !== undefined) {
            return new CrosswordDimensions(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read CrosswordDimensions from input");
        }
    }
}
