/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ICrosswordPositionArgs {
    x: number;
    y: number;
}
export class CrosswordPosition {
    public x: number;
    public y: number;
    constructor(args: ICrosswordPositionArgs) {
        if (args != null && args.x != null) {
            this.x = args.x;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[x] is unset!");
        }
        if (args != null && args.y != null) {
            this.y = args.y;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[y] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CrosswordPosition");
        if (this.x != null) {
            output.writeFieldBegin("x", thrift.TType.I32, 1);
            output.writeI32(this.x);
            output.writeFieldEnd();
        }
        if (this.y != null) {
            output.writeFieldBegin("y", thrift.TType.I32, 2);
            output.writeI32(this.y);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CrosswordPosition {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.x = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: number = input.readI32();
                        _args.y = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.x !== undefined && _args.y !== undefined) {
            return new CrosswordPosition(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read CrosswordPosition from input");
        }
    }
}
