/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as ElementType from "./ElementType";
import * as Asset from "./Asset";
export interface IElementArgs {
    id: string;
    relation: string;
    type: ElementType.ElementType;
    galleryIndex?: number;
    assets: Array<Asset.Asset>;
}
export class Element {
    public id: string;
    public relation: string;
    public type: ElementType.ElementType;
    public galleryIndex?: number;
    public assets: Array<Asset.Asset>;
    constructor(args: IElementArgs) {
        if (args != null && args.id != null) {
            this.id = args.id;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[id] is unset!");
        }
        if (args != null && args.relation != null) {
            this.relation = args.relation;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[relation] is unset!");
        }
        if (args != null && args.type != null) {
            this.type = args.type;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[type] is unset!");
        }
        if (args != null && args.galleryIndex != null) {
            this.galleryIndex = args.galleryIndex;
        }
        if (args != null && args.assets != null) {
            this.assets = args.assets;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[assets] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Element");
        if (this.id != null) {
            output.writeFieldBegin("id", thrift.TType.STRING, 1);
            output.writeString(this.id);
            output.writeFieldEnd();
        }
        if (this.relation != null) {
            output.writeFieldBegin("relation", thrift.TType.STRING, 2);
            output.writeString(this.relation);
            output.writeFieldEnd();
        }
        if (this.type != null) {
            output.writeFieldBegin("type", thrift.TType.I32, 3);
            output.writeI32(this.type);
            output.writeFieldEnd();
        }
        if (this.galleryIndex != null) {
            output.writeFieldBegin("galleryIndex", thrift.TType.I32, 4);
            output.writeI32(this.galleryIndex);
            output.writeFieldEnd();
        }
        if (this.assets != null) {
            output.writeFieldBegin("assets", thrift.TType.LIST, 5);
            output.writeListBegin(thrift.TType.STRUCT, this.assets.length);
            this.assets.forEach((value_1: Asset.Asset): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Element {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.id = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.relation = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.I32) {
                        const value_4: ElementType.ElementType = input.readI32();
                        _args.type = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.I32) {
                        const value_5: number = input.readI32();
                        _args.galleryIndex = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.TType.LIST) {
                        const value_6: Array<Asset.Asset> = new Array<Asset.Asset>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_7: Asset.Asset = Asset.Asset.read(input);
                            value_6.push(value_7);
                        }
                        input.readListEnd();
                        _args.assets = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.id !== undefined && _args.relation !== undefined && _args.type !== undefined && _args.assets !== undefined) {
            return new Element(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read Element from input");
        }
    }
}
