/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IEmbedElementFieldsArgs {
    html?: string;
    safeEmbedCode?: boolean;
    alt?: string;
    isMandatory?: boolean;
}
export class EmbedElementFields {
    public html?: string;
    public safeEmbedCode?: boolean;
    public alt?: string;
    public isMandatory?: boolean;
    constructor(args?: IEmbedElementFieldsArgs) {
        if (args != null && args.html != null) {
            this.html = args.html;
        }
        if (args != null && args.safeEmbedCode != null) {
            this.safeEmbedCode = args.safeEmbedCode;
        }
        if (args != null && args.alt != null) {
            this.alt = args.alt;
        }
        if (args != null && args.isMandatory != null) {
            this.isMandatory = args.isMandatory;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("EmbedElementFields");
        if (this.html != null) {
            output.writeFieldBegin("html", thrift.TType.STRING, 1);
            output.writeString(this.html);
            output.writeFieldEnd();
        }
        if (this.safeEmbedCode != null) {
            output.writeFieldBegin("safeEmbedCode", thrift.TType.BOOL, 2);
            output.writeBool(this.safeEmbedCode);
            output.writeFieldEnd();
        }
        if (this.alt != null) {
            output.writeFieldBegin("alt", thrift.TType.STRING, 3);
            output.writeString(this.alt);
            output.writeFieldEnd();
        }
        if (this.isMandatory != null) {
            output.writeFieldBegin("isMandatory", thrift.TType.BOOL, 4);
            output.writeBool(this.isMandatory);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): EmbedElementFields {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.html = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.BOOL) {
                        const value_2: boolean = input.readBool();
                        _args.safeEmbedCode = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.alt = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.BOOL) {
                        const value_4: boolean = input.readBool();
                        _args.isMandatory = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new EmbedElementFields(_args);
    }
}
