/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as Content from "./Content";
export interface IPackageArticleArgs {
    content: Content.Content;
}
export class PackageArticle {
    public content: Content.Content;
    constructor(args: IPackageArticleArgs) {
        if (args != null && args.content != null) {
            this.content = args.content;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[content] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("PackageArticle");
        if (this.content != null) {
            output.writeFieldBegin("content", thrift.TType.STRUCT, 2);
            this.content.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): PackageArticle {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 2:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_1: Content.Content = Content.Content.read(input);
                        _args.content = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.content !== undefined) {
            return new PackageArticle(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read PackageArticle from input");
        }
    }
}
