/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ISponsorshipLogoDimensionsArgs {
    width: number;
    height: number;
}
export class SponsorshipLogoDimensions {
    public width: number;
    public height: number;
    constructor(args: ISponsorshipLogoDimensionsArgs) {
        if (args != null && args.width != null) {
            this.width = args.width;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[width] is unset!");
        }
        if (args != null && args.height != null) {
            this.height = args.height;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[height] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("SponsorshipLogoDimensions");
        if (this.width != null) {
            output.writeFieldBegin("width", thrift.TType.I32, 1);
            output.writeI32(this.width);
            output.writeFieldEnd();
        }
        if (this.height != null) {
            output.writeFieldBegin("height", thrift.TType.I32, 2);
            output.writeI32(this.height);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): SponsorshipLogoDimensions {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.width = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.I32) {
                        const value_2: number = input.readI32();
                        _args.height = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.width !== undefined && _args.height !== undefined) {
            return new SponsorshipLogoDimensions(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read SponsorshipLogoDimensions from input");
        }
    }
}
