/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as MostViewedVideo from "./MostViewedVideo";
export interface IVideoStatsResponseArgs {
    status: string;
    mostViewedVideos: Array<MostViewedVideo.MostViewedVideo>;
}
export class VideoStatsResponse {
    public status: string;
    public mostViewedVideos: Array<MostViewedVideo.MostViewedVideo>;
    constructor(args: IVideoStatsResponseArgs) {
        if (args != null && args.status != null) {
            this.status = args.status;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[status] is unset!");
        }
        if (args != null && args.mostViewedVideos != null) {
            this.mostViewedVideos = args.mostViewedVideos;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[mostViewedVideos] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VideoStatsResponse");
        if (this.status != null) {
            output.writeFieldBegin("status", thrift.TType.STRING, 1);
            output.writeString(this.status);
            output.writeFieldEnd();
        }
        if (this.mostViewedVideos != null) {
            output.writeFieldBegin("mostViewedVideos", thrift.TType.LIST, 2);
            output.writeListBegin(thrift.TType.STRUCT, this.mostViewedVideos.length);
            this.mostViewedVideos.forEach((value_1: MostViewedVideo.MostViewedVideo): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VideoStatsResponse {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.status = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.LIST) {
                        const value_3: Array<MostViewedVideo.MostViewedVideo> = new Array<MostViewedVideo.MostViewedVideo>();
                        const metadata_1: thrift.IThriftList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: MostViewedVideo.MostViewedVideo = MostViewedVideo.MostViewedVideo.read(input);
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.mostViewedVideos = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.status !== undefined && _args.mostViewedVideos !== undefined) {
            return new VideoStatsResponse(_args);
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read VideoStatsResponse from input");
        }
    }
}
