/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IVideoElementFieldsArgs {
    url?: string;
    description?: string;
    title?: string;
    html?: string;
    source?: string;
    credit?: string;
    caption?: string;
    height?: number;
    width?: number;
    duration?: number;
    contentAuthSystem?: string;
    embeddable?: string;
    isInappropriateForAdverts?: boolean;
    mediaId?: string;
    stillImageUrl?: string;
    thumbnailUrl?: string;
    shortUrl?: string;
    role?: string;
    originalUrl?: string;
}
export class VideoElementFields {
    public url?: string;
    public description?: string;
    public title?: string;
    public html?: string;
    public source?: string;
    public credit?: string;
    public caption?: string;
    public height?: number;
    public width?: number;
    public duration?: number;
    public contentAuthSystem?: string;
    public embeddable?: string;
    public isInappropriateForAdverts?: boolean;
    public mediaId?: string;
    public stillImageUrl?: string;
    public thumbnailUrl?: string;
    public shortUrl?: string;
    public role?: string;
    public originalUrl?: string;
    constructor(args?: IVideoElementFieldsArgs) {
        if (args != null && args.url != null) {
            this.url = args.url;
        }
        if (args != null && args.description != null) {
            this.description = args.description;
        }
        if (args != null && args.title != null) {
            this.title = args.title;
        }
        if (args != null && args.html != null) {
            this.html = args.html;
        }
        if (args != null && args.source != null) {
            this.source = args.source;
        }
        if (args != null && args.credit != null) {
            this.credit = args.credit;
        }
        if (args != null && args.caption != null) {
            this.caption = args.caption;
        }
        if (args != null && args.height != null) {
            this.height = args.height;
        }
        if (args != null && args.width != null) {
            this.width = args.width;
        }
        if (args != null && args.duration != null) {
            this.duration = args.duration;
        }
        if (args != null && args.contentAuthSystem != null) {
            this.contentAuthSystem = args.contentAuthSystem;
        }
        if (args != null && args.embeddable != null) {
            this.embeddable = args.embeddable;
        }
        if (args != null && args.isInappropriateForAdverts != null) {
            this.isInappropriateForAdverts = args.isInappropriateForAdverts;
        }
        if (args != null && args.mediaId != null) {
            this.mediaId = args.mediaId;
        }
        if (args != null && args.stillImageUrl != null) {
            this.stillImageUrl = args.stillImageUrl;
        }
        if (args != null && args.thumbnailUrl != null) {
            this.thumbnailUrl = args.thumbnailUrl;
        }
        if (args != null && args.shortUrl != null) {
            this.shortUrl = args.shortUrl;
        }
        if (args != null && args.role != null) {
            this.role = args.role;
        }
        if (args != null && args.originalUrl != null) {
            this.originalUrl = args.originalUrl;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VideoElementFields");
        if (this.url != null) {
            output.writeFieldBegin("url", thrift.TType.STRING, 1);
            output.writeString(this.url);
            output.writeFieldEnd();
        }
        if (this.description != null) {
            output.writeFieldBegin("description", thrift.TType.STRING, 2);
            output.writeString(this.description);
            output.writeFieldEnd();
        }
        if (this.title != null) {
            output.writeFieldBegin("title", thrift.TType.STRING, 3);
            output.writeString(this.title);
            output.writeFieldEnd();
        }
        if (this.html != null) {
            output.writeFieldBegin("html", thrift.TType.STRING, 4);
            output.writeString(this.html);
            output.writeFieldEnd();
        }
        if (this.source != null) {
            output.writeFieldBegin("source", thrift.TType.STRING, 5);
            output.writeString(this.source);
            output.writeFieldEnd();
        }
        if (this.credit != null) {
            output.writeFieldBegin("credit", thrift.TType.STRING, 6);
            output.writeString(this.credit);
            output.writeFieldEnd();
        }
        if (this.caption != null) {
            output.writeFieldBegin("caption", thrift.TType.STRING, 7);
            output.writeString(this.caption);
            output.writeFieldEnd();
        }
        if (this.height != null) {
            output.writeFieldBegin("height", thrift.TType.I32, 8);
            output.writeI32(this.height);
            output.writeFieldEnd();
        }
        if (this.width != null) {
            output.writeFieldBegin("width", thrift.TType.I32, 9);
            output.writeI32(this.width);
            output.writeFieldEnd();
        }
        if (this.duration != null) {
            output.writeFieldBegin("duration", thrift.TType.I32, 10);
            output.writeI32(this.duration);
            output.writeFieldEnd();
        }
        if (this.contentAuthSystem != null) {
            output.writeFieldBegin("contentAuthSystem", thrift.TType.STRING, 11);
            output.writeString(this.contentAuthSystem);
            output.writeFieldEnd();
        }
        if (this.embeddable != null) {
            output.writeFieldBegin("embeddable", thrift.TType.STRING, 12);
            output.writeString(this.embeddable);
            output.writeFieldEnd();
        }
        if (this.isInappropriateForAdverts != null) {
            output.writeFieldBegin("isInappropriateForAdverts", thrift.TType.BOOL, 13);
            output.writeBool(this.isInappropriateForAdverts);
            output.writeFieldEnd();
        }
        if (this.mediaId != null) {
            output.writeFieldBegin("mediaId", thrift.TType.STRING, 14);
            output.writeString(this.mediaId);
            output.writeFieldEnd();
        }
        if (this.stillImageUrl != null) {
            output.writeFieldBegin("stillImageUrl", thrift.TType.STRING, 15);
            output.writeString(this.stillImageUrl);
            output.writeFieldEnd();
        }
        if (this.thumbnailUrl != null) {
            output.writeFieldBegin("thumbnailUrl", thrift.TType.STRING, 16);
            output.writeString(this.thumbnailUrl);
            output.writeFieldEnd();
        }
        if (this.shortUrl != null) {
            output.writeFieldBegin("shortUrl", thrift.TType.STRING, 17);
            output.writeString(this.shortUrl);
            output.writeFieldEnd();
        }
        if (this.role != null) {
            output.writeFieldBegin("role", thrift.TType.STRING, 18);
            output.writeString(this.role);
            output.writeFieldEnd();
        }
        if (this.originalUrl != null) {
            output.writeFieldBegin("originalUrl", thrift.TType.STRING, 19);
            output.writeString(this.originalUrl);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VideoElementFields {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.url = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.description = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.title = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.TType.STRING) {
                        const value_4: string = input.readString();
                        _args.html = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.TType.STRING) {
                        const value_5: string = input.readString();
                        _args.source = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.TType.STRING) {
                        const value_6: string = input.readString();
                        _args.credit = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.TType.STRING) {
                        const value_7: string = input.readString();
                        _args.caption = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.TType.I32) {
                        const value_8: number = input.readI32();
                        _args.height = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.TType.I32) {
                        const value_9: number = input.readI32();
                        _args.width = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.TType.I32) {
                        const value_10: number = input.readI32();
                        _args.duration = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.TType.STRING) {
                        const value_11: string = input.readString();
                        _args.contentAuthSystem = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.TType.STRING) {
                        const value_12: string = input.readString();
                        _args.embeddable = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.TType.BOOL) {
                        const value_13: boolean = input.readBool();
                        _args.isInappropriateForAdverts = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.TType.STRING) {
                        const value_14: string = input.readString();
                        _args.mediaId = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.TType.STRING) {
                        const value_15: string = input.readString();
                        _args.stillImageUrl = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.TType.STRING) {
                        const value_16: string = input.readString();
                        _args.thumbnailUrl = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.TType.STRING) {
                        const value_17: string = input.readString();
                        _args.shortUrl = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.TType.STRING) {
                        const value_18: string = input.readString();
                        _args.role = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.TType.STRING) {
                        const value_19: string = input.readString();
                        _args.originalUrl = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new VideoElementFields(_args);
    }
}
