//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


declare class CalculatorClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  ping(): void;

  ping(callback: (data: void)=>void): void;

  add(num1: number, num2: number): number;

  add(num1: number, num2: number, callback: (data: number)=>void): void;
}
