name: Validate

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4
            - uses: guardian/actions-setup-node@main
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: node-
            - name: install
              run: npm ci
            - name: lint
              run: npm run lint
            - name: test
              run: npm run test
            - name: compile client
              run: npm run build:client:prod
            - name: compile server
              run: npm run build:server:prod
