name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup dependencies
      uses: ./.github/actions/setup-apps-rendering/action.yml
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: compile client
      run: npm run build:client:prod
    - name: compile server
      run: npm run build:server:prod
