name: Screenshots

on:
  pull_request:

jobs:
  screenshots:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-    
    - name: install
      run: npm ci
    - name: run
      run: |
        npm install -g ngrok
        npm run watch & 
        sleep 20s
      env: 
        APIS_IMG_SALT: ${{ secrets.APIS_IMG_SALT }}  
        CAPI_KEY: ${{ secrets.CAPI_KEY }}
    - name: Take screenshot of apps-rendering
      uses: "lannonbr/puppeteer-screenshot-action@1.3.0"
      with:
        url: http://localhost:8080/
    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots 
