name: Screenshots

on:
  pull_request:

jobs:
  screenshots:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-    
    - name: install
      run: npm ci
    - name: run
      run: |
        npm install -g ngrok
        npm run watch & 
        sleep 60s
      env: 
        APIS_IMG_SALT: ${{ secrets.APIS_IMG_SALT }}  
        CAPI_KEY: ${{ secrets.CAPI_KEY }}
    - name: Take screenshot of apps-rendering
      uses: "lannonbr/puppeteer-screenshot-action@1.3.0"
      with:
        url: http://localhost:8080/
    - name: Upload screenshot
      run: echo "to do"
    - name: post onto PR
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ![image](https://gu-mobile-pr-images.s3-eu-west-1.amazonaws.com/edb8f441ce8df55b2296a58492d402f100692118/politics/2020/oct/01/brexit-eu-launches-legal-action-against-uk-for-breaching-withdrawal-agreement/screenshot.png)
        repo-token: ${{ secrets.GITHUB_TOKEN }}  
