name: Screenshots

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  screenshots:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node-
    - name: install
      run: npm ci
    - name: run
      run: |
        npm run watch &
        sleep 60s
      env:
        APIS_IMG_SALT: ${{ secrets.APIS_IMG_SALT }}
        CAPI_KEY: ${{ secrets.CAPI_KEY }}
    - name: Take screenshot of apps-rendering
      uses: "lannonbr/puppeteer-screenshot-action@1.3.0"
      with:
        url: http://localhost:8080/
    - name: Upload screenshot
      run: aws s3 cp screenshots/screenshot*.png s3://gu-mobile-pr-images/8a293ad6dae4620d19dd3ee9985f0f58f896f5e1/screenshot.png --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CI_IMAGE_UPLOADER_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_IMAGE_UPLOADER_SECRET_ACCESS_KEY }}
