name: Screenshots

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    article_screenshots:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                article:
                    - format: Standard
                      url: http://localhost:8080/uk-news/2020/nov/12/stonehenge-road-tunnel-given-go-ahead-despite-backlash
                    - format: Immersive
                      url: 'http://localhost:8080/news/2020/nov/12/western-travel-influencers-social-media-pakistan-politics'
                    - format: Feature
                      url: 'http://localhost:8080/fashion/2020/nov/12/rainbow-bright-how-the-symbol-of-optimism-and-joy-spread-across-our-clothes-homes-and-lives-in-2020'
                    - format: Gallery
                      url: 'http://localhost:8080/news/gallery/2020/nov/12/morning-fog-and-a-dog-in-deep-water-thursdays-best-photos'
                    - format: Opinion
                      url: 'http://localhost:8080/commentisfree/2020/nov/12/lee-cain-no-10-boris-johnson-chief-of-staff-britain'
                    - format: Review
                      url: 'http://localhost:8080/film/2020/nov/12/billie-review-singer-documentary-historical-voice-harassment-exploitation'
                    - format: Analysis
                      url: 'http://localhost:8080/us-news/2020/nov/13/joe-biden-cabinet-selection-trump-obstruction'
                    - format: 'EditionsStandard'
                      url: 'http://localhost:8080/uk-news/2020/nov/12/stonehenge-road-tunnel-given-go-ahead-despite-backlash?editions'
                    - format: 'EditionsOpinion'
                      url: 'http://localhost:8080/commentisfree/2020/nov/12/lee-cain-no-10-boris-johnson-chief-of-staff-britain?editions'
                    - format: 'EditionsReview'
                      url: 'http://localhost:8080/film/2020/nov/12/billie-review-singer-documentary-historical-voice-harassment-exploitation?editions'
                    - format: 'EditionsInterview'
                      url: 'http://localhost:8080/sport/2021/jan/24/ollie-lawrence-i-wanted-to-emulate-tuilagi-because-his-play-excited-me?editions'
                    - format: 'EditionsAnalysis'
                      url: 'http://localhost:8080/money/2021/jan/20/why-uk-house-prices-jumped-in-november-stamp-duty?editions'
                    - format: 'EditionsShowcase'
                      url: 'http://localhost:8080/tv-and-radio/2020/jul/12/michaela-coel-profile-i-may-destroy-you-trauma-into-cultural-triumph?editions'
                    - format: 'EditionsImmersive'
                      url: 'http://localhost:8080/society/2019/dec/17/decade-of-perpetual-crisis-2010s-disrupted-everything-but-resolved-nothing?editions'
                    - format: 'EditionsGallery'
                      url: 'http://localhost:8080/us-news/gallery/2021/jan/20/joe-biden-inauguration-46th-president-united-states-in-pictures?editions'


        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: node-
            - name: install
              run: npm ci
            - name: run
              run: |
                  npm run watch &
                  sleep 45s
              env:
                  APIS_IMG_SALT: ${{ secrets.APIS_IMG_SALT }}
                  CAPI_KEY: ${{ secrets.CAPI_KEY }}

            - name: Take screenshot of apps-rendering
              uses: 'lannonbr/puppeteer-screenshot-action@1.3.1'
              with:
                  url: ${{ matrix.article.url }}
            - name: Upload screenshot
              id: upload
              run: |
                  aws s3 cp screenshots/screenshot*.png s3://gu-mobile-pr-images/${{ github.sha }}/${{ matrix.article.format }}/screenshot.png --acl public-read
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.CI_IMAGE_UPLOADER_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_IMAGE_UPLOADER_SECRET_ACCESS_KEY }}

    comment:
        runs-on: ubuntu-18.04
        needs: article_screenshots
        strategy:
            max-parallel: 1
            matrix:
                article:
                    - format: Standard
                      url: http://localhost:8080/uk-news/2020/nov/12/stonehenge-road-tunnel-given-go-ahead-despite-backlash
                    - format: Immersive
                      url: 'http://localhost:8080/news/2020/nov/12/western-travel-influencers-social-media-pakistan-politics'
                    - format: Feature
                      url: 'http://localhost:8080/fashion/2020/nov/12/rainbow-bright-how-the-symbol-of-optimism-and-joy-spread-across-our-clothes-homes-and-lives-in-2020'
                    - format: Gallery
                      url: 'http://localhost:8080/news/gallery/2020/nov/12/morning-fog-and-a-dog-in-deep-water-thursdays-best-photos'
                    - format: Opinion
                      url: 'http://localhost:8080/commentisfree/2020/nov/12/lee-cain-no-10-boris-johnson-chief-of-staff-britain'
                    - format: Review
                      url: 'http://localhost:8080/film/2020/nov/12/billie-review-singer-documentary-historical-voice-harassment-exploitation'
                    - format: Analysis
                      url: 'http://localhost:8080/us-news/2020/nov/13/joe-biden-cabinet-selection-trump-obstruction'
                    - format: 'EditionsStandard'
                      url: 'http://localhost:8080/uk-news/2020/nov/12/stonehenge-road-tunnel-given-go-ahead-despite-backlash?editions'
                    - format: 'EditionsOpinion'
                      url: 'http://localhost:8080/commentisfree/2020/nov/12/lee-cain-no-10-boris-johnson-chief-of-staff-britain?editions'
                    - format: 'EditionsReview'
                      url: 'http://localhost:8080/film/2020/nov/12/billie-review-singer-documentary-historical-voice-harassment-exploitation?editions'

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Prepare image urls
              id: image-urls
              if: ${{ github.ref != 'main' }}
              run: |
                  MAIN_COMMIT_SHA=$(git show-ref main --hash)
                  echo "::set-output name=before::https://gu-mobile-pr-images.s3-eu-west-1.amazonaws.com/$MAIN_COMMIT_SHA/${{ matrix.article.format }}/screenshot.png"
                  echo "::set-output name=after::https://gu-mobile-pr-images.s3-eu-west-1.amazonaws.com/${{ github.sha }}/${{ matrix.article.format }}/screenshot.png"
            - uses: peter-evans/find-comment@v1
              if: ${{ github.event_name == 'pull_request' }}
              id: find
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body-includes: <!-- github-actions-screenshots -->

            - name: Create comment is necessary
              if: ${{ github.event_name == 'pull_request' && steps.find.outputs.comment-id == '' && matrix.article.format == 'Standard' }}
              uses: peter-evans/create-or-update-comment@v1
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      <!-- github-actions-screenshots -->
                      ### ${{ matrix.article.format }}
                      | Before | After |
                      | --- | --- |
                      | <img src="${{ steps.image-urls.outputs.before }}" width="350px" /> | <img src="${{ steps.image-urls.outputs.after }}" width="350px" /> |

            - name: Update comment is necessary
              if: ${{ github.event_name == 'pull_request' && steps.find.outputs.comment-id != '' && matrix.article.format == 'Standard' }}
              uses: peter-evans/create-or-update-comment@v1
              with:
                  comment-id: ${{ steps.find.outputs.comment-id }}
                  body: |
                      <!-- github-actions-screenshots -->
                      ### ${{ matrix.article.format }}
                      | Before | After |
                      | --- | --- |
                      | <img src="${{ steps.image-urls.outputs.before }}" width="350px" /> | <img src="${{ steps.image-urls.outputs.after }}" width="350px" /> |
                  edit-mode: replace

            - name: Append other article screenshots
              if: ${{ github.event_name == 'pull_request' && matrix.article.format != 'Standard' }}
              uses: peter-evans/create-or-update-comment@v1
              with:
                  comment-id: ${{ steps.find.outputs.comment-id }}
                  body: |
                      <!-- github-actions-screenshots -->
                      ### ${{ matrix.article.format }}
                      | Before | After |
                      | --- | --- |
                      | <img src="${{ steps.image-urls.outputs.before }}" width="350px" /> | <img src="${{ steps.image-urls.outputs.after }}" width="350px" /> |
                  edit-mode: append
